### PR TITLE
feat: Client#refreshToken should refresh OAuth Access Token

### PR DESCRIPTION
**Pull request by tejasmanohar**
forgot to PR this for a while, def major version up / breaking changes :P

### CODE REVIEW

**Comment by brainflake** [comment]
I like it. do we need to pass the new refresh token back along w/ the new access token in refreshAccessToken?

**Comment by tejasmanohar** [comment]
Refresh token is immutable / never expires. API response returns it- no clue why.

**Comment by brainflake** [comment]
Gotcha. Do they say that anywhere in the docs, or is it just assumed? I know the refresh tokens should only be generated by the auth endpoint, but HS tends to do it's own thing w/ their oauth implementation

**Comment by tejasmanohar** [comment]
@brainflake assumed, i'll re-assign it from the response since there's no harm (hopefully). will do so after making a few other changes- in b/w a project using my branch rn

**Comment by brainflake** [comment]
sounds good @tejasmanohar . thanks

**Comment by pcothenet** [comment]
@tejasmanohar I'm re-implementing something similar in the new version of the connector.

**Comment by pcothenet** [comment]
Added equivalent method to 1.0 #48

**Pull request closed without merging**
