### PR TITLE
Feat/timeline + Prettier

### PR DESCRIPTION
**Pull request by Oupsla**
⚠️  Do not merge yet ⚠️ 

First draft of the implementation of the timeline API
I'll continue to work on this next week I hope (help on this is welcome 😄 )

I have also run prettier on the project (if you don't like it, tell me and I'll remove the commit)

Resolving : https://github.com/brainflake/node-hubspot/issues/81

### CODE REVIEW

**Comment by pcothenet** [comment]
Hi @Oupsla, thanks for the PR. 

For prettier, not a problem.

**Comment by Oupsla** [comment]
Hello @pcothenet ,

I have tried this code on my project today and it is working great ! 
Just to mention, to use timeline api, people need to init the library with client_id and client_secret and have to not set the api_key or the hubspot api will reject all calls.

For me, it seems ok to merge it right now (even with some functions missing).
I don't know how to test it without client_id and client_secret for tests.

**Comment by MattMSumner** [comment]
@Oupsla Thanks for doing this. I'd love to get this merged!

I hope you don't mind but I've pulled down this branch and rebased to try and get the test running. Once I've done that, I may open a new PR and link to it from here. Or I could open a PR against your branch if you would prefer.

**Comment by Oupsla** [comment]
Hello @MattMSumner 
It has been a long time since I didn't touch this branch so feel free to do what you want with it !

Maybe the best way will be to create a new branch from master and just cherry-pick this commit : https://github.com/MadKudu/node-hubspot/pull/90/commits/49c0da252649bb43e200f00d7b7b32b6d9fb3999 

To prettier everything I suggest to use https://github.com/prettier/prettier-eslint and add this line in package.json 
`"format": "prettier-eslint --write \"src/**/*.js\"`

----- EDIT ----- 
I can do it tomorrow. I'll rebase this pull request just for the Timeline feat and remove the prettier part  (I just see eslint and prettier have been set in package.json now)

**Comment by MattMSumner** [comment]
@Oupsla sweet! After diving in I realized I'd need to setup oauth to get this working. Were you using an oauth token you generated locally for the ENV variables you had set?

**Comment by Oupsla** [comment]
Yeah, I have created an application on hubspot and I have done the "dancing" oauth phase for only one account (I don't need this application on other hubspot account or to share this app, it is specific to my business).
So I have generated a token and a refresh token that I use when I need to use the timeline API

**Pull request closed without merging**
