### PR TITLE
 Methods Test

### PR DESCRIPTION
**Pull request by fbritoferreira**

### CODE REVIEW

**Comment by iTsFILIPOficial** [comment]
@brainflake Just finishing writing test that will check for basic functionality, this can be improved over time but should test all the required functionality.

Closes #10 
Closes #25

**Comment by fbritoferreira** [comment]
@brainflake Just finishing writing test that will check for basic functionality, this can be improved over time but should test all the required functionality.

Closes #10 
Closes #25

**Comment by fbritoferreira** [comment]
@brainflake it would be good to setup the main repo with travis ci so we can see build status, also code coverage.

**Comment by fbritoferreira** [comment]
@brainflake What do you think of the tests?

**Comment by brainflake** [comment]
Was just looking at it. The tests are great. Glad to have increased coverage. I'm thinking we might want to trim down the config files you included though.

**Comment by brainflake** [comment]
@iTsFILIPOficial The PR looks good, I'm just going to tweak the code climate + eslint configs after I merge it. Thanks for adding all of these tests!

**Comment by fbritoferreira** [comment]
@brainflake Thanks, also it would be good if you could setup the travis ci for the project so we can run tests before merges.

**Comment by brainflake** [comment]
Yep, already setup travis.

**Pull request merged**
