### PR TITLE
Bumped dependencies versions

### LINKED ISSUE #36: vulnerability in request
Hey guys, any chance of a bump on the version number of request (>=v2.74.0)? Current one you are using is insecure:

https://nodesecurity.io/check/hubspot

Great tool by the way!

### PR DESCRIPTION
**Pull request by fbritoferreira**
Closes #36 

Updated all dependencies.

### CODE REVIEW

**Comment by fbritoferreira** [comment]
@brainflake For some reason the api demo key is giving you http error 429 to many request not sure this is a change on hubspots side or something we need to look at.

**Comment by fbritoferreira** [comment]
@brainflake I have updated the test due to the demo api key not being working.

**Comment by brainflake** [comment]
Thanks @iTsFILIPOficial 

Where'd you get that key? Is it from a personal account of yours?

**Comment by fbritoferreira** [comment]
@brainflake i created a test dev account that we can use as suggested by the hubsporters in the forum.

**Comment by brainflake** [comment]
Ah, got ya. Thanks for doing that.

**Pull request merged**
