### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by brainflake**
Flesh out readme a bit

### CODE REVIEW

**Comment by timisbusy** [comment]
I think key and token are optional; you need to use one or the other. We may want to clarify that.

**Comment by brainflake** [comment]
Ah, good call. Let me add something

**Comment by brainflake** [comment]
@tejasmanohar @kr1sp1n I'm planning on merging these open PRs unless you object

**Comment by tejasmanohar** [comment]
LGTM

**Pull request merged**
