### PR TITLE
Remove unnecessary slash in URL

### PR DESCRIPTION
**Pull request by jlaneve**

### CODE REVIEW

**Comment by fbritoferreira** [comment]
@jlaneve That / is needed as most methods don't have a / before the link.

**Comment by brainflake** [comment]
Yeah, they can probably be more consistent. If you wanted to make sure there's a slash before all of the methods I'm fine with changing it.

**Comment by fbritoferreira** [comment]
@brainflake @jlaneve on the pull request #25 I have change it so all methods have the slash before the link instead of the base url

**Comment by brainflake** [comment]
:+1: thanks @iTsFILIPOficial ! Closing this PR then

**Pull request closed without merging**
