### PR TITLE
Add option to ignore limit check, use headers for limit check

### PR DESCRIPTION
**Pull request by AustinLeeGordon**
# Why

Currently uses up 2 API calls for each call. This adds a simple option to the constructor to ignore it:

```javascript
const Hubspot = require('hubspot');
const hubspot = new Hubspot({
    apiKey: 'key',
    checkLimit: false // Ignores API limit check
});
```

A more elegant solution needs to be put in place for rate limit checking (something involving the [API response headers](https://developers.hubspot.com/docs/faq/working-within-the-hubspot-api-rate-limits)), so this will be removed in the future.

This change addresses the need by:

- Relates to #51 

Also

- fixed npm scripts and prettier/editorconfig settings to work cross env 
- and corrected some style issues in contributing.md and README.md.

### CODE REVIEW

**Comment by AustinLeeGordon** [comment]
Realized that the `maxUsePercent` option already allows for ignoring the check. I'm almost finished implementing a fix using headers from the API response.

**Comment by pcothenet** [comment]
Awesome PR @AustinLeeGordon . Really appreciated!

I think I had confirmed with HubSpot that the checkLimit call does not count towards the API limit but I see the need for making it less chatty.

**Comment by AustinLeeGordon** [comment]
Commit 76e937e uses response headers from each request to update the current usage. @pcothenet You're right - tested `getApiLimit` and it didn't count toward the usage. Definitely better to only make one request though!

I left in `getApiLimit` even though it's not being used in the request. I figured it was still useful for specifically checking the limit. Also keeps the tests passing.

The request doesn't do a check on the first call since `updateApiLimit` is called after receiving the first response. I can add in a conditional to fall back on `getApiLimit` for the first request and update the `usageLimit` and `currentUsage` from it if you'd like!

**Comment by chrisbaldauf** [comment]
@pcothenet I checked and the [Check daily API usage](https://developers.hubspot.com/docs/methods/check-daily-api-usage) endpoint does actually count against the daily and burst (per second) limit. I'm going to look into whether or not we can _safely_ relax that restriction. 

In general, I recommend using the `x-hubspot-ratelimit-*` headers, but please be aware that those headers will be absent when using OAuth tokens or in some exceptional cases.

Disclaimer: I work for HubSpot

I ran this experiment against an isolated account and I'm sure this was the only API traffic in flight at the time.

```
$ curl https://api.hubapi.com/integrations/v1/limit/daily?hapikey=$HK -i
HTTP/1.1 200 OK
...
X-HubSpot-RateLimit-Daily: 40000
X-HubSpot-RateLimit-Daily-Remaining: 39999
X-HubSpot-RateLimit-Secondly: 10
X-HubSpot-RateLimit-Secondly-Remaining: 9
...

$ curl https://api.hubapi.com/integrations/v1/limit/daily?hapikey=$HK -i
HTTP/1.1 200 OK
...
X-HubSpot-RateLimit-Daily: 40000
X-HubSpot-RateLimit-Daily-Remaining: 39998
X-HubSpot-RateLimit-Secondly: 10
X-HubSpot-RateLimit-Secondly-Remaining: 9
...
```

**Comment by AustinLeeGordon** [comment]
@chrisbaldauf Thanks for checking into that! For some reason it seemed to count for mine in some cases but didn't in others. Might have just missed something. The latest few commits in this thread change it to check from the `x-hubspot-ratelimit-*` headers instead of making another call.

**Comment by pcothenet** [comment]
Thanks @chrisbaldauf @AustinLeeGordon . I'll be able to review and hopefully GTM this weekend.

**Comment by pcothenet** [comment]
@chrisbaldauf can you also shed some light on why the headers are not returned when using OAuth? Seems like a surprising design decision, no?

**Comment by AustinLeeGordon** [comment]
Hey @pcothenet! Any update on this? Let me know if there's anything I can do to help!

**Comment by pcothenet** [comment]
@AustinLeeGordon I'm still quite confused by @chrisbaldauf comment about "please be aware that those headers will be absent when using OAuth tokens".

I know that in my use case, I was relying on this check to not blow up the API limit (and we're using OAuth)

**Comment by pcothenet** [comment]
But all things considered, I think this is an improvement. Merging.

**Comment by AustinLeeGordon** [comment]
@pcothenet Glad to see it go through! I haven’t used it with OAuth, but does it typically count toward the api count whenever using OAuth? If not, then this shouldn’t add any unnecessary calls, it just wouldn’t check the headers for it.

**Pull request merged**
