### PR TITLE
Feature: Add hubspot.deals.updateBatch(data)

### PR DESCRIPTION
**Pull request by MSWagner**
Why:

- To update a group of deals using the batch-async endpoint 
-> works like hubspot.companies.updateBatch(data)

[Hubspot Deals API - Update a group of deals](https://developers.hubspot.com/docs/methods/deals/batch-update-deals)

### CODE REVIEW

**Comment by pcothenet** [comment]
@SGrondin would you be able to check @SGrondin 's recommendation and fix the conflict?

**Comment by SGrondin** [comment]
@pcothenet I think there's a mistake in your message?

**Comment by MSWagner** [comment]
@pcothenet There is no conflict from my code. Your tests have failed before...check the details to see which tests are broken.

@SGrondin Thanks for the recommendation.

**Comment by pcothenet** [comment]
> @pcothenet I think there's a mistake in your message?

Aha, yeah. Thanks for pointing it out :)

**Comment by pcothenet** [comment]
> @pcothenet There is no conflict from my code. Your tests have failed before...check the details to see which tests are broken.
> 
> @SGrondin Thanks for the recommendation.

Thanks for adding. I fixed a conflict with master, should be all good now.

And yeah, the tests are unfortunately way too flaky.

**Review by pcothenet — APPROVED** [review]

**Pull request merged**
